version: '2.1'
services:
  openvpn:
    sysctls:
     - net.ipv4.ip_forward=1
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "3333:1194/udp"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
     - /home/adad/vpn-data:/etc/openvpn